#import "CHAppLibraryController.h"
#import "CHInstalledAppCatalog.h"
#import "CHProfileStore.h"
#import "CHMapController.h"

@interface CHAppProfilesController : UITableViewController
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, strong) NSDictionary *application;
@property(nonatomic, copy) NSArray<NSDictionary *> *profiles;
@end

@interface CHAppLibraryController () <UISearchResultsUpdating>
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, copy) NSArray<NSDictionary *> *applications;
@property(nonatomic, copy) NSArray<NSDictionary *> *visibleApplications;
@property(nonatomic, copy) NSArray<NSString *> *sectionTitles;
@property(nonatomic, copy) NSArray<NSArray<NSDictionary *> *> *sectionedApplications;
@property(nonatomic, strong) UISearchController *searchController;
@end

@interface CHProfileDetailController ()
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, strong) NSDictionary *application;
@property(nonatomic, copy) NSString *profileID;
@end

static void CHPromptText(UIViewController *controller, NSString *title, NSString *message, NSString *value, void (^completion)(NSString *)) {
    UIAlertController *alert = [UIAlertController alertControllerWithTitle:title message:message preferredStyle:UIAlertControllerStyleAlert]; [alert addTextFieldWithConfigurationHandler:^(UITextField *field) { field.text = value ?: @""; field.clearButtonMode = UITextFieldViewModeWhileEditing; }]; [alert addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; [alert addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { NSString *text = [alert.textFields.firstObject.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; if (text.length) completion(text); }]]; [controller presentViewController:alert animated:YES completion:nil];
}

@implementation CHAppLibraryController
- (instancetype)initWithStore:(CHProfileStore *)store { if ((self = [super initWithStyle:UITableViewStyleInsetGrouped])) _store = store; return self; }
- (void)viewDidLoad { [super viewDidLoad]; self.title = @"Applications"; self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeAlways; self.overrideUserInterfaceStyle = UIUserInterfaceStyleDark; self.tableView.backgroundColor = UIColor.blackColor; self.tableView.separatorColor = [UIColor colorWithWhite:1 alpha:.10]; self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil]; self.searchController.searchResultsUpdater = self; self.searchController.obscuresBackgroundDuringPresentation = NO; self.searchController.searchBar.placeholder = @"Search"; self.navigationItem.searchController = self.searchController; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(reloadApplications)]; [self reloadApplications]; }
- (void)reloadApplications { self.applications = [CHInstalledAppCatalog thirdPartyApplications]; [self updateSearchResultsForSearchController:self.searchController]; }
- (void)updateSearchResultsForSearchController:(UISearchController *)searchController { NSString *query = searchController.searchBar.text.lowercaseString; self.visibleApplications = query.length ? [self.applications filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary *app, NSDictionary *bindings) { return [[app[@"name"] lowercaseString] containsString:query] || [[app[@"bundleID"] lowercaseString] containsString:query]; }]] : self.applications; NSMutableDictionary *groups = [NSMutableDictionary dictionary]; for (NSDictionary *app in self.visibleApplications) { NSString *key = [app[@"name"] substringToIndex:MIN((NSUInteger)1, [app[@"name"] length])]; key = [key uppercaseString]; if (![[NSCharacterSet letterCharacterSet] characterIsMember:[key characterAtIndex:0]]) key = @"#"; groups[key] = [groups[key] arrayByAddingObject:app] ?: @[app]; } self.sectionTitles = [[groups.allKeys sortedArrayUsingSelector:@selector(compare:)] copy]; NSMutableArray *sections = [NSMutableArray array]; for (NSString *key in self.sectionTitles) [sections addObject:[groups[key] sortedArrayUsingDescriptors:@[[NSSortDescriptor sortDescriptorWithKey:@"name" ascending:YES]]]]; self.sectionedApplications = sections; [self.tableView reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return MAX((NSUInteger)1, self.sectionTitles.count); }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return self.sectionedApplications.count ? self.sectionedApplications[section].count : 1; }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return self.sectionedApplications.count ? self.sectionTitles[section] : nil; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { return section == self.sectionedApplications.count - 1 ? @"Only third-party user applications are shown." : nil; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath { UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; cell.backgroundColor = [UIColor colorWithWhite:.11 alpha:1]; cell.textLabel.textColor = UIColor.whiteColor; cell.detailTextLabel.textColor = UIColor.secondaryLabelColor; cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator; if (!self.sectionedApplications.count) { cell.textLabel.text = @"No third-party apps detected"; return cell; } NSDictionary *app = self.sectionedApplications[indexPath.section][indexPath.row]; NSUInteger count = 0; for (NSDictionary *profile in self.store.profiles) if ([profile[@"apps"] containsObject:app[@"bundleID"]]) count++; cell.textLabel.text = app[@"name"]; cell.detailTextLabel.text = count ? [NSString stringWithFormat:@"%lu container%@", (unsigned long)count, count == 1 ? @"" : @"s"] : app[@"bundleID"]; cell.imageView.image = app[@"icon"] ?: [UIImage systemImageNamed:@"app.fill"]; cell.imageView.layer.cornerRadius = 10; cell.imageView.layer.masksToBounds = YES; return cell; }
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath { [tableView deselectRowAtIndexPath:indexPath animated:YES]; if (!self.sectionedApplications.count) return; CHAppProfilesController *profiles = [[CHAppProfilesController alloc] initWithStyle:UITableViewStyleInsetGrouped]; profiles.store = self.store; profiles.application = self.sectionedApplications[indexPath.section][indexPath.row]; [self.navigationController pushViewController:profiles animated:YES]; }
@end

@implementation CHAppProfilesController
- (void)viewDidLoad { [super viewDidLoad]; self.title = self.application[@"name"]; self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd target:self action:@selector(createProfile)]; }
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; [self reloadProfiles]; }
- (void)reloadProfiles { NSMutableArray *items = [NSMutableArray array]; for (NSDictionary *profile in self.store.profiles) if ([profile[@"apps"] containsObject:self.application[@"bundleID"]]) [items addObject:profile]; self.profiles = items; [self.tableView reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return 2; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return section == 0 ? 1 : MAX((NSUInteger)1, self.profiles.count); }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return section == 0 ? @"Application" : @"App Profiles"; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { return section == 1 ? @"Each profile belongs to this app and has its own proxy, location and profile metadata." : nil; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath { UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; if (indexPath.section == 0) { cell.textLabel.text = self.application[@"name"]; cell.detailTextLabel.text = self.application[@"bundleID"]; cell.imageView.image = self.application[@"icon"] ?: [UIImage systemImageNamed:@"app.fill"]; cell.accessoryType = UITableViewCellAccessoryNone; } else if (!self.profiles.count) { cell.textLabel.text = @"Create the first profile"; cell.detailTextLabel.text = @"Tap + or this row"; cell.imageView.image = [UIImage systemImageNamed:@"plus.circle.fill"]; cell.imageView.tintColor = UIColor.systemGreenColor; cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator; } else { NSDictionary *profile = self.profiles[indexPath.row]; BOOL active = [profile[@"id"] isEqual:self.store.activeProfileID]; cell.textLabel.text = profile[@"name"]; cell.detailTextLabel.text = active ? @"Running now" : @"Inactive"; cell.imageView.image = [UIImage systemImageNamed:active ? @"checkmark.circle.fill" : @"circle"]; cell.imageView.tintColor = active ? UIColor.systemGreenColor : UIColor.tertiaryLabelColor; cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator; } return cell; }
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath { [tableView deselectRowAtIndexPath:indexPath animated:YES]; if (indexPath.section == 0) return; if (!self.profiles.count) { [self createProfile]; return; } NSDictionary *profile = self.profiles[indexPath.row]; [self.navigationController pushViewController:[[CHProfileDetailController alloc] initWithStore:self.store application:self.application profileID:profile[@"id"]] animated:YES]; }
- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)style forRowAtIndexPath:(NSIndexPath *)indexPath { if (indexPath.section != 1 || !self.profiles.count || style != UITableViewCellEditingStyleDelete) return; NSDictionary *profile = self.profiles[indexPath.row]; NSUInteger storeIndex = [self.store.profiles indexOfObjectPassingTest:^BOOL(NSDictionary *item, NSUInteger idx, BOOL *stop) { return [item[@"id"] isEqual:profile[@"id"]]; }]; [self.store deleteProfileAtIndex:storeIndex]; [self reloadProfiles]; }
- (void)createProfile { NSString *suggested = [NSString stringWithFormat:@"%@ %lu", self.application[@"name"], (unsigned long)self.profiles.count + 1]; CHPromptText(self, @"New App Profile", @"This profile will belong only to the selected app.", suggested, ^(NSString *name) { [self.store addProfileNamed:name]; NSUInteger index = self.store.profiles.count - 1; [self.store addBundleID:self.application[@"bundleID"] toProfileAtIndex:index]; [self.store activateProfileAtIndex:index]; NSDictionary *profile = self.store.profiles[index]; [self reloadProfiles]; [self.navigationController pushViewController:[[CHProfileDetailController alloc] initWithStore:self.store application:self.application profileID:profile[@"id"]] animated:YES]; }); }
@end

@implementation CHProfileDetailController
- (instancetype)initWithStore:(CHProfileStore *)store application:(NSDictionary *)application profileID:(NSString *)profileID { if ((self = [super initWithStyle:UITableViewStyleInsetGrouped])) { _store = store; _application = application; _profileID = [profileID copy]; } return self; }
- (void)viewDidLoad { [super viewDidLoad]; self.title = self.application[@"name"]; self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever; self.overrideUserInterfaceStyle = UIUserInterfaceStyleDark; self.tableView.backgroundColor = UIColor.blackColor; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd target:self action:@selector(createContainer)]; }
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; [self.tableView reloadData]; }
- (NSUInteger)profileIndex { return [self.store.profiles indexOfObjectPassingTest:^BOOL(NSDictionary *profile, NSUInteger idx, BOOL *stop) { return [profile[@"id"] isEqual:self.profileID]; }]; }
- (NSDictionary *)profile { NSUInteger index = self.profileIndex; return index == NSNotFound ? nil : self.store.profiles[index]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return 7; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { if (section == 0) return 3; if (section == 1) return 2; if (section == 2) return 5; if (section == 3) return 1; if (section == 4) return [self.store containersForProfileAtIndex:self.profileIndex].count + 1; return 1; }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return @[@"Session", @"Configuration", @"Profile Metadata", @"Application", @"Containers", @"Notifications", @"Container Protection"][section]; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { if (section == 2) return @"Aliases are editable profile metadata; protected hardware identifiers are not changed."; if (section == 4) return @"Switching the active data container requires relaunching the target app."; if (section == 5) return @"Separate notification registrations keep container sessions distinguishable."; if (section == 6) return @"Prevents accidental removal of a container’s app data."; return nil; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    NSDictionary *profile = self.profile; UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:nil];
    if (indexPath.section == 0) { if (indexPath.row == 0) { cell.textLabel.text = @"Status"; cell.detailTextLabel.text = [profile[@"id"] isEqual:self.store.activeProfileID] ? @"Running" : @"Inactive"; cell.imageView.image = [UIImage systemImageNamed:@"power"]; } else if (indexPath.row == 1) { cell.textLabel.text = @"Activate Profile"; cell.imageView.image = [UIImage systemImageNamed:@"checkmark.circle.fill"]; cell.imageView.tintColor = UIColor.systemGreenColor; } else { cell.textLabel.text = @"Launch Application"; cell.imageView.image = self.application[@"icon"] ?: [UIImage systemImageNamed:@"arrow.up.forward.app.fill"]; } cell.accessoryType = indexPath.row ? UITableViewCellAccessoryDisclosureIndicator : UITableViewCellAccessoryNone; }
    else if (indexPath.section == 1) { if (indexPath.row == 0) { NSDictionary *proxy = profile[@"proxy"]; cell.textLabel.text = @"Proxy"; cell.detailTextLabel.text = [proxy[@"enabled"] boolValue] ? (proxy[@"host"] ?: @"Enabled") : @"Off"; cell.imageView.image = [UIImage systemImageNamed:@"network"]; UISwitch *toggle = [UISwitch new]; toggle.tag = 100; toggle.on = [proxy[@"enabled"] boolValue]; [toggle addTarget:self action:@selector(featureToggled:) forControlEvents:UIControlEventValueChanged]; cell.accessoryView = toggle; } else { NSDictionary *location = profile[@"location"]; cell.textLabel.text = @"Location"; cell.detailTextLabel.text = [location[@"enabled"] boolValue] ? @"Configured" : @"Off"; cell.imageView.image = [UIImage systemImageNamed:@"map.fill"]; UISwitch *toggle = [UISwitch new]; toggle.tag = 101; toggle.on = [location[@"enabled"] boolValue]; [toggle addTarget:self action:@selector(featureToggled:) forControlEvents:UIControlEventValueChanged]; cell.accessoryView = toggle; } }
    else if (indexPath.section == 2) { NSArray *titles = @[@"Profile Name", @"Profile ID", @"Vendor Alias", @"Advertising Alias", @"Session Label"]; NSArray *keys = @[@"", @"", @"vendorAlias", @"advertisingAlias", @"sessionLabel"]; cell.textLabel.text = titles[indexPath.row]; if (indexPath.row == 0) cell.detailTextLabel.text = profile[@"name"]; else if (indexPath.row == 1) cell.detailTextLabel.text = [profile[@"id"] substringToIndex:MIN((NSUInteger)8, [profile[@"id"] length])]; else cell.detailTextLabel.text = profile[@"metadata"][keys[indexPath.row]] ?: @"Not set"; cell.accessoryType = indexPath.row == 1 ? UITableViewCellAccessoryNone : UITableViewCellAccessoryDisclosureIndicator; }
    else if (indexPath.section == 3) { cell.textLabel.text = self.application[@"name"]; cell.detailTextLabel.text = self.application[@"bundleID"]; cell.imageView.image = self.application[@"icon"] ?: [UIImage systemImageNamed:@"app.fill"]; cell.accessoryType = UITableViewCellAccessoryNone; }
    else if (indexPath.section == 4) { NSArray *containers = [self.store containersForProfileAtIndex:self.profileIndex]; if (indexPath.row == containers.count) { cell.textLabel.text = @"Add"; cell.textLabel.textColor = UIColor.systemBlueColor; cell.imageView.image = [UIImage systemImageNamed:@"plus"]; } else { NSDictionary *container = containers[indexPath.row]; BOOL active = [container[@"id"] isEqual:[self.store activeContainerIDForProfileAtIndex:self.profileIndex]]; cell.textLabel.text = container[@"name"]; cell.detailTextLabel.text = active ? @"Active container" : @"Inactive"; cell.imageView.image = [UIImage systemImageNamed:active ? @"checkmark.circle.fill" : @"shippingbox.fill"]; cell.imageView.tintColor = active ? UIColor.systemGreenColor : UIColor.secondaryLabelColor; } cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator; }
    else if (indexPath.section == 5 || indexPath.section == 6) { NSString *key = indexPath.section == 5 ? @"separateNotifications" : @"containerProtection"; cell.textLabel.text = indexPath.section == 5 ? @"Separate Notification Registrations" : @"Container Protection"; cell.detailTextLabel.text = indexPath.section == 5 ? @"Use separate notification state per container." : @"Protect container data from accidental removal."; UISwitch *toggle = [UISwitch new]; toggle.tag = indexPath.section == 5 ? 200 : 201; toggle.on = [self.profile[@"containerOptions"][key] boolValue]; [toggle addTarget:self action:@selector(containerOptionToggled:) forControlEvents:UIControlEventValueChanged]; cell.accessoryView = toggle; cell.accessoryType = UITableViewCellAccessoryNone; }
    return cell;
}
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath { [tableView deselectRowAtIndexPath:indexPath animated:YES]; NSDictionary *profile = self.profile; if (indexPath.section == 0) { if (indexPath.row == 1) { [self.store activateProfileAtIndex:self.profileIndex]; [tableView reloadData]; } else if (indexPath.row == 2) { [self.store activateProfileAtIndex:self.profileIndex]; Class workspaceClass = NSClassFromString(@"LSApplicationWorkspace"); id workspace = [workspaceClass performSelector:@selector(defaultWorkspace)]; if ([workspace respondsToSelector:@selector(openApplicationWithBundleID:)]) [workspace performSelector:@selector(openApplicationWithBundleID:) withObject:self.application[@"bundleID"]]; } return; } if (indexPath.section == 1) { if (indexPath.row == 0) [self configureProxy]; else [self configureLocation]; return; } if (indexPath.section == 4) { NSArray *containers = [self.store containersForProfileAtIndex:self.profileIndex]; if (indexPath.row == containers.count) [self createContainer]; else { [self.store activateContainerID:containers[indexPath.row][@"id"] forProfileAtIndex:self.profileIndex]; [tableView reloadData]; } return; } if (indexPath.section == 5 || indexPath.section == 6) return; if (indexPath.section != 2) return; if (indexPath.row == 1) { UIPasteboard.generalPasteboard.string = profile[@"id"]; return; } NSArray *keys = @[@"", @"", @"vendorAlias", @"advertisingAlias", @"sessionLabel"]; NSString *key = keys[indexPath.row]; NSString *current = indexPath.row == 0 ? profile[@"name"] : profile[@"metadata"][key]; CHPromptText(self, indexPath.row == 0 ? @"Profile Name" : [tableView cellForRowAtIndexPath:indexPath].textLabel.text, nil, current, ^(NSString *value) { if (indexPath.row == 0) [self.store renameProfileAtIndex:self.profileIndex name:value]; else [self.store setMetadataValue:value forKey:key profileAtIndex:self.profileIndex]; [self.tableView reloadData]; }); }
- (void)featureToggled:(UISwitch *)toggle { if (toggle.tag == 100) [self.store setProxyEnabled:toggle.on forProfileAtIndex:self.profileIndex]; else [self.store setLocationEnabled:toggle.on forProfileAtIndex:self.profileIndex]; [self.tableView reloadData]; }
- (void)configureProxy { NSDictionary *proxy = self.profile[@"proxy"]; UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Proxy" message:@"Configure this app profile." preferredStyle:UIAlertControllerStyleAlert]; for (NSString *placeholder in @[@"Host", @"Port", @"Username (optional)", @"Password (optional)"]) [alert addTextFieldWithConfigurationHandler:^(UITextField *field) { field.placeholder = placeholder; field.secureTextEntry = [placeholder hasPrefix:@"Password"]; if ([placeholder isEqualToString:@"Port"]) field.keyboardType = UIKeyboardTypeNumberPad; }]; NSArray *values = @[proxy[@"host"] ?: @"", proxy[@"port"] ? [proxy[@"port"] stringValue] : @"", proxy[@"username"] ?: @"", proxy[@"password"] ?: @""]; [alert.textFields enumerateObjectsUsingBlock:^(UITextField *field, NSUInteger idx, BOOL *stop) { field.text = values[idx]; }]; [alert addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; [alert addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { [self.store setProxyHost:alert.textFields[0].text port:[alert.textFields[1].text integerValue] username:alert.textFields[2].text password:alert.textFields[3].text forProfileAtIndex:self.profileIndex]; [self.tableView reloadData]; }]]; [self presentViewController:alert animated:YES completion:nil]; }
- (void)configureLocation { [self.store activateProfileAtIndex:self.profileIndex]; CHMapController *map = [CHMapController new]; map.store = self.store; map.profileIndex = self.profileIndex; [self presentViewController:[[UINavigationController alloc] initWithRootViewController:map] animated:YES completion:nil]; }
- (void)createContainer { CHPromptText(self, @"New data container", @"Create an isolated app data session for this profile.", [NSString stringWithFormat:@"Session %lu", (unsigned long)[self.store containersForProfileAtIndex:self.profileIndex].count + 1], ^(NSString *name) { [self.store createContainerNamed:name forProfileAtIndex:self.profileIndex]; [self.tableView reloadData]; }); }
- (void)containerOptionToggled:(UISwitch *)toggle { [self.store setContainerOption:toggle.on key:(toggle.tag == 200 ? @"separateNotifications" : @"containerProtection") forProfileAtIndex:self.profileIndex]; [self.tableView reloadData]; }
@end
