#import "CHAppLibraryController.h"
#import "CHInstalledAppCatalog.h"
#import "CHProfileStore.h"
#import "CHMapController.h"

static void CHPromptText(UIViewController *controller, NSString *title, NSString *message, NSString *value, void (^completion)(NSString *)) {
    UIAlertController *a = [UIAlertController alertControllerWithTitle:title message:message preferredStyle:UIAlertControllerStyleAlert];
    [a addTextFieldWithConfigurationHandler:^(UITextField *f) { f.text = value ?: @""; f.clearButtonMode = UITextFieldViewModeWhileEditing; }];
    [a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];
    [a addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x) { NSString *v = [a.textFields.firstObject.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; if (v.length) completion(v); }]];
    [controller presentViewController:a animated:YES completion:nil];
}

@interface CHAppContainersController : UITableViewController
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, strong) NSDictionary *application;
@property(nonatomic, copy) NSArray<NSDictionary *> *containers;
@end
@interface CHAppLibraryController () <UISearchResultsUpdating>
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, copy) NSArray<NSDictionary *> *applications, *visibleApplications;
@property(nonatomic, copy) NSArray<NSString *> *sectionTitles;
@property(nonatomic, copy) NSArray<NSArray<NSDictionary *> *> *sectionedApplications;
@property(nonatomic, strong) UISearchController *searchController;
@end
@interface CHProfileDetailController ()
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, strong) NSDictionary *application;
@property(nonatomic, copy) NSString *profileID;
@end

@implementation CHAppLibraryController
- (instancetype)initWithStore:(CHProfileStore *)store { if ((self = [super initWithStyle:UITableViewStyleInsetGrouped])) _store = store; return self; }
- (void)viewDidLoad { [super viewDidLoad]; self.title = @"Applications"; self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeAlways; self.overrideUserInterfaceStyle = UIUserInterfaceStyleDark; self.tableView.backgroundColor = UIColor.blackColor; self.tableView.separatorColor = [UIColor colorWithWhite:1 alpha:.1]; self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil]; self.searchController.searchResultsUpdater = self; self.searchController.obscuresBackgroundDuringPresentation = NO; self.searchController.searchBar.placeholder = @"Search installed apps"; self.navigationItem.searchController = self.searchController; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(reloadApplications)]; [self reloadApplications]; }
- (void)reloadApplications { self.applications = [CHInstalledAppCatalog thirdPartyApplications]; [self updateSearchResultsForSearchController:self.searchController]; }
- (void)updateSearchResultsForSearchController:(UISearchController *)sc { NSString *q = sc.searchBar.text.lowercaseString; self.visibleApplications = q.length ? [self.applications filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary *app, NSDictionary *b) { return [[app[@"name"] lowercaseString] containsString:q] || [[app[@"bundleID"] lowercaseString] containsString:q]; }]] : self.applications; NSMutableDictionary *groups = [NSMutableDictionary dictionary]; for (NSDictionary *app in self.visibleApplications) { NSString *name = app[@"name"] ?: @"#"; NSString *key = name.length ? [[name substringToIndex:1] uppercaseString] : @"#"; if (![[NSCharacterSet letterCharacterSet] characterIsMember:[key characterAtIndex:0]]) key = @"#"; groups[key] = groups[key] ? [groups[key] arrayByAddingObject:app] : @[app]; } self.sectionTitles = [[groups.allKeys sortedArrayUsingSelector:@selector(compare:)] copy]; NSMutableArray *sections = [NSMutableArray array]; for (NSString *key in self.sectionTitles) [sections addObject:[groups[key] sortedArrayUsingDescriptors:@[[NSSortDescriptor sortDescriptorWithKey:@"name" ascending:YES]]]]; self.sectionedApplications = sections; [self.tableView reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t { return MAX((NSUInteger)1, self.sectionTitles.count); }
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s { return self.sectionedApplications.count ? self.sectionedApplications[s].count : 1; }
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s { return self.sectionedApplications.count ? self.sectionTitles[s] : nil; }
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s { return s == self.sectionedApplications.count - 1 ? @"Only installed third-party applications are shown." : nil; }
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p { UITableViewCell *c = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; c.backgroundColor = [UIColor colorWithWhite:.11 alpha:1]; c.textLabel.textColor = UIColor.whiteColor; c.detailTextLabel.textColor = UIColor.secondaryLabelColor; c.accessoryType = UITableViewCellAccessoryDisclosureIndicator; if (!self.sectionedApplications.count) { c.textLabel.text = @"No third-party apps detected"; return c; } NSDictionary *app = self.sectionedApplications[p.section][p.row]; NSUInteger n = 0; for (NSDictionary *e in self.store.profiles) if ([e[@"apps"] containsObject:app[@"bundleID"]]) n++; c.textLabel.text = app[@"name"]; c.detailTextLabel.text = n ? [NSString stringWithFormat:@"%lu container%@", (unsigned long)n, n == 1 ? @"" : @"s"] : app[@"bundleID"]; c.imageView.image = app[@"icon"] ?: [UIImage systemImageNamed:@"app.fill"]; c.imageView.layer.cornerRadius = 10; c.imageView.layer.masksToBounds = YES; return c; }
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p { [t deselectRowAtIndexPath:p animated:YES]; if (!self.sectionedApplications.count) return; CHAppContainersController *vc = [CHAppContainersController new]; vc.store = self.store; vc.application = self.sectionedApplications[p.section][p.row]; [self.navigationController pushViewController:vc animated:YES]; }
@end

@implementation CHAppContainersController
- (void)viewDidLoad { [super viewDidLoad]; self.title = @"Containers"; self.overrideUserInterfaceStyle = UIUserInterfaceStyleDark; self.tableView.backgroundColor = UIColor.blackColor; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd target:self action:@selector(createContainer)]; UILongPressGestureRecognizer *g = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(longPressed:)]; g.minimumPressDuration = .45; [self.tableView addGestureRecognizer:g]; }
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; [self reloadContainers]; }
- (void)reloadContainers { NSMutableArray *a = [NSMutableArray array]; for (NSDictionary *e in self.store.profiles) if ([e[@"apps"] containsObject:self.application[@"bundleID"]]) [a addObject:e]; self.containers = a; [self.tableView reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t { return 2; }
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s { return s == 0 ? 1 : MAX((NSUInteger)1, self.containers.count); }
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s { return s == 0 ? @"Application" : @"App containers"; }
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s { return s == 1 ? @"Tap a container to open it. Long-press for settings and generated identifiers." : nil; }
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p { UITableViewCell *c = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; c.backgroundColor = [UIColor colorWithWhite:.11 alpha:1]; c.textLabel.textColor = UIColor.whiteColor; c.detailTextLabel.textColor = UIColor.secondaryLabelColor; if (p.section == 0) { c.textLabel.text = self.application[@"name"]; c.detailTextLabel.text = self.application[@"bundleID"]; c.imageView.image = self.application[@"icon"] ?: [UIImage systemImageNamed:@"app.fill"]; return c; } if (!self.containers.count) { c.textLabel.text = @"Create the first container"; c.detailTextLabel.text = @"Tap + to create an app-specific session"; c.imageView.image = [UIImage systemImageNamed:@"plus.circle.fill"]; c.imageView.tintColor = UIColor.systemGreenColor; c.accessoryType = UITableViewCellAccessoryDisclosureIndicator; return c; } NSDictionary *e = self.containers[p.row]; BOOL active = [e[@"id"] isEqual:self.store.activeProfileID]; c.textLabel.text = e[@"name"] ?: @"Container"; c.detailTextLabel.text = [NSString stringWithFormat:@"%@  •  %@", active ? @"Running" : @"Ready", [e[@"id"] substringToIndex:MIN((NSUInteger)8, [e[@"id"] length])]]; c.imageView.image = [UIImage systemImageNamed:active ? @"checkmark.circle.fill" : @"shippingbox.fill"]; c.imageView.tintColor = active ? UIColor.systemGreenColor : UIColor.secondaryLabelColor; c.accessoryType = UITableViewCellAccessoryDisclosureIndicator; return c; }
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p { [t deselectRowAtIndexPath:p animated:YES]; if (p.section != 1) return; if (!self.containers.count) { [self createContainer]; return; } [self openContainer:self.containers[p.row]]; }
- (void)longPressed:(UILongPressGestureRecognizer *)g { if (g.state != UIGestureRecognizerStateBegan) return; NSIndexPath *p = [self.tableView indexPathForRowAtPoint:[g locationInView:self.tableView]]; if (p && p.section == 1 && p.row < self.containers.count) [self openContainer:self.containers[p.row]]; }
- (void)openContainer:(NSDictionary *)e { [self.navigationController pushViewController:[[CHProfileDetailController alloc] initWithStore:self.store application:self.application profileID:e[@"id"]] animated:YES]; }
- (void)createContainer { NSString *s = [NSString stringWithFormat:@"Container %lu", (unsigned long)self.containers.count + 1]; CHPromptText(self, @"New container", @"Create an app-owned data session.", s, ^(NSString *name) { [self.store addProfileNamed:name]; NSUInteger i = self.store.profiles.count - 1; [self.store addBundleID:self.application[@"bundleID"] toProfileAtIndex:i]; [self.store activateProfileAtIndex:i]; [self reloadContainers]; [self openContainer:self.store.profiles[i]]; }); }
@end

@implementation CHProfileDetailController
- (instancetype)initWithStore:(CHProfileStore *)store application:(NSDictionary *)application profileID:(NSString *)profileID { if ((self = [super initWithStyle:UITableViewStyleInsetGrouped])) { _store = store; _application = application; _profileID = [profileID copy]; } return self; }
- (void)viewDidLoad { [super viewDidLoad]; self.title = @"Container Settings"; self.overrideUserInterfaceStyle = UIUserInterfaceStyleDark; self.tableView.backgroundColor = UIColor.blackColor; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemPlay target:self action:@selector(launchApp)]; }
- (NSUInteger)profileIndex { return [self.store.profiles indexOfObjectPassingTest:^BOOL(NSDictionary *e, NSUInteger i, BOOL *stop) { return [e[@"id"] isEqual:self.profileID]; }]; }
- (NSDictionary *)profile { NSUInteger i = self.profileIndex; return i == NSNotFound ? nil : self.store.profiles[i]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t { return 5; }
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s { return s == 0 ? 4 : (s == 1 ? 2 : (s == 2 ? 4 : 1)); }
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s { return @[@"Identity", @"Runtime", @"Generated values", @"Container options", @"Launch"][s]; }
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s { if (s == 0) return @"Values belong to this app container. Protected hardware identifiers are not collected or changed."; if (s == 2) return @"Generate creates fresh local session aliases."; return nil; }
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p { NSDictionary *e = self.profile; UITableViewCell *c = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:nil]; c.backgroundColor = [UIColor colorWithWhite:.11 alpha:1]; c.textLabel.textColor = UIColor.whiteColor; c.detailTextLabel.textColor = UIColor.secondaryLabelColor; if (p.section == 0) { NSArray *l = @[@"Application", @"Bundle ID", @"Container ID", @"Container name"]; c.textLabel.text = l[p.row]; c.detailTextLabel.text = p.row == 0 ? self.application[@"name"] : (p.row == 1 ? self.application[@"bundleID"] : (p.row == 2 ? e[@"id"] : e[@"name"])); c.accessoryType = p.row == 3 ? UITableViewCellAccessoryDisclosureIndicator : UITableViewCellAccessoryNone; } else if (p.section == 1) { NSDictionary *proxy = e[@"proxy"], *loc = e[@"location"]; c.textLabel.text = p.row == 0 ? @"Proxy" : @"Location"; c.detailTextLabel.text = p.row == 0 ? ([proxy[@"enabled"] boolValue] ? (proxy[@"host"] ?: @"Enabled") : @"Off") : ([loc[@"enabled"] boolValue] ? (loc[@"label"] ?: @"Configured") : @"Off"); c.accessoryType = UITableViewCellAccessoryDisclosureIndicator; } else if (p.section == 2) { NSArray *l = @[@"Vendor alias", @"Advertising alias", @"Session label", @"Generate fresh values"]; NSArray *k = @[@"vendorAlias", @"advertisingAlias", @"sessionLabel", @""]; c.textLabel.text = l[p.row]; c.detailTextLabel.text = p.row < 3 ? (e[@"metadata"][k[p.row]] ?: @"Not set") : @"UUID aliases"; c.accessoryType = UITableViewCellAccessoryDisclosureIndicator; } else if (p.section == 3) { c.textLabel.text = @"Container protection"; c.detailTextLabel.text = [e[@"containerOptions"][@"containerProtection"] boolValue] ? @"On" : @"Off"; UISwitch *sw = [UISwitch new]; sw.on = [e[@"containerOptions"][@"containerProtection"] boolValue]; sw.tag = 201; [sw addTarget:self action:@selector(optionChanged:) forControlEvents:UIControlEventValueChanged]; c.accessoryView = sw; } else { c.textLabel.text = @"Launch application"; c.imageView.image = self.application[@"icon"] ?: [UIImage systemImageNamed:@"arrow.up.forward.app.fill"]; c.accessoryType = UITableViewCellAccessoryDisclosureIndicator; } return c; }
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p { [t deselectRowAtIndexPath:p animated:YES]; if (p.section == 0 && p.row == 3) { CHPromptText(self, @"Container name", nil, self.profile[@"name"], ^(NSString *v) { [self.store renameProfileAtIndex:self.profileIndex name:v]; [self.tableView reloadData]; }); } else if (p.section == 1) { if (p.row == 0) [self configureProxy]; else [self configureLocation]; } else if (p.section == 2) { if (p.row < 3) { NSArray *k = @[@"vendorAlias", @"advertisingAlias", @"sessionLabel"]; CHPromptText(self, @[@"Vendor alias", @"Advertising alias", @"Session label"][p.row], nil, self.profile[@"metadata"][k[p.row]], ^(NSString *v) { [self.store setMetadataValue:v forKey:k[p.row] profileAtIndex:self.profileIndex]; [self.tableView reloadData]; }); } else [self generateValues]; } else if (p.section == 4) [self launchApp]; }
- (void)generateValues { for (NSString *k in @[@"vendorAlias", @"advertisingAlias", @"sessionLabel"]) [self.store setMetadataValue:NSUUID.UUID.UUIDString.lowercaseString forKey:k profileAtIndex:self.profileIndex]; [self.tableView reloadData]; }
- (void)optionChanged:(UISwitch *)sw { [self.store setContainerOption:sw.on key:@"containerProtection" forProfileAtIndex:self.profileIndex]; }
- (void)configureProxy { NSDictionary *p = self.profile[@"proxy"]; UIAlertController *a = [UIAlertController alertControllerWithTitle:@"Proxy" message:@"Configure this app container." preferredStyle:UIAlertControllerStyleAlert]; for (NSString *s in @[@"Host", @"Port", @"Username (optional)", @"Password (optional)"]) [a addTextFieldWithConfigurationHandler:^(UITextField *f) { f.placeholder = s; f.secureTextEntry = [s hasPrefix:@"Password"]; if ([s isEqualToString:@"Port"]) f.keyboardType = UIKeyboardTypeNumberPad; }]; NSArray *v = @[p[@"host"] ?: @"", p[@"port"] ? [p[@"port"] stringValue] : @"", p[@"username"] ?: @"", p[@"password"] ?: @""]; [a.textFields enumerateObjectsUsingBlock:^(UITextField *f, NSUInteger i, BOOL *stop) { f.text = v[i]; }]; [a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; [a addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x) { [self.store setProxyHost:a.textFields[0].text port:[a.textFields[1].text integerValue] username:a.textFields[2].text password:a.textFields[3].text forProfileAtIndex:self.profileIndex]; [self.tableView reloadData]; }]]; [self presentViewController:a animated:YES completion:nil]; }
- (void)configureLocation { CHMapController *m = [CHMapController new]; m.store = self.store; m.profileIndex = self.profileIndex; [self presentViewController:[[UINavigationController alloc] initWithRootViewController:m] animated:YES completion:nil]; }
- (void)launchApp { Class c = NSClassFromString(@"LSApplicationWorkspace"); id w = [c performSelector:@selector(defaultWorkspace)]; if ([w respondsToSelector:@selector(openApplicationWithBundleID:)]) [w performSelector:@selector(openApplicationWithBundleID:) withObject:self.application[@"bundleID"]]; [self.store activateProfileAtIndex:self.profileIndex]; }
@end
