#import "CHRootViewController.h"
#import "CHProfileStore.h"
#import "CHInstalledAppCatalog.h"
#import "CHMapController.h"
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>

@interface CHRootViewController () <UIDocumentPickerDelegate, UISearchResultsUpdating>
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, copy) NSArray<NSDictionary *> *installedApps;
@property(nonatomic, copy) NSArray<NSDictionary *> *visibleApps;
@property(nonatomic, strong) UISearchController *searchController;
@end

@implementation CHRootViewController
- (void)viewDidLoad {
    [super viewDidLoad]; self.title = @"Chameleon"; self.store = [CHProfileStore new]; self.navigationController.navigationBar.prefersLargeTitles = YES; self.navigationController.navigationBar.tintColor = UIColor.systemGreenColor; self.tableView.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd target:self action:@selector(addProfile)]; self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(reloadInstalledApps)];
    self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil]; self.searchController.searchResultsUpdater = self; self.searchController.obscuresBackgroundDuringPresentation = NO; self.searchController.searchBar.placeholder = @"Search installed apps"; self.navigationItem.searchController = self.searchController; self.definesPresentationContext = YES;
    [self reloadInstalledApps];
}
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; [self.tableView reloadData]; }
- (void)reloadInstalledApps { self.installedApps = [CHInstalledAppCatalog thirdPartyApplications]; [self updateSearchResultsForSearchController:self.searchController]; }
- (void)updateSearchResultsForSearchController:(UISearchController *)searchController { NSString *query = searchController.searchBar.text.lowercaseString; if (!query.length) self.visibleApps = self.installedApps; else self.visibleApps = [self.installedApps filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary *app, NSDictionary *bindings) { return [app[@"name"] lowercaseString].length && ([[app[@"name"] lowercaseString] containsString:query] || [[app[@"bundleID"] lowercaseString] containsString:query]); }]]; [self.tableView reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return 4; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { if (section == 0) return 1; if (section == 1) return self.visibleApps.count; if (section == 2) return self.store.profiles.count; return 5; }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return @[@"Overview", @"Installed Apps", @"Profiles", @"Tools"][section]; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { if (section == 1) return self.visibleApps.count ? @"Tap an app to create a new profile or add it to the active profile." : @"No third-party user applications were detected. Tap refresh after installing an app."; if (section == 2) return @"Profiles are created automatically from the app list, or manually with +."; return nil; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    if (indexPath.section == 0) {
        NSDictionary *active = self.store.activeProfile; cell.textLabel.text = active ? active[@"name"] : @"Choose an app to begin"; cell.detailTextLabel.text = active ? [NSString stringWithFormat:@"Active · %lu app%@", (unsigned long)[active[@"apps"] count], [active[@"apps"] count] == 1 ? @"" : @"s"] : [NSString stringWithFormat:@"%lu third-party apps detected", (unsigned long)self.installedApps.count]; cell.imageView.image = [UIImage systemImageNamed:active ? @"checkmark.shield.fill" : @"wand.and.stars"]; cell.imageView.tintColor = UIColor.systemGreenColor; cell.accessoryType = UITableViewCellAccessoryNone;
    } else if (indexPath.section == 1) {
        NSDictionary *app = self.visibleApps[indexPath.row]; NSDictionary *profile = [self profileForBundleID:app[@"bundleID"]]; cell.textLabel.text = app[@"name"]; cell.detailTextLabel.text = profile ? [NSString stringWithFormat:@"%@ · %@", app[@"bundleID"], profile[@"name"]] : app[@"bundleID"]; cell.imageView.image = app[@"icon"] ?: [UIImage systemImageNamed:@"app.fill"]; cell.imageView.layer.cornerRadius = 10; cell.imageView.layer.masksToBounds = YES; cell.accessoryType = profile ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryDisclosureIndicator;
    } else if (indexPath.section == 2) {
        NSDictionary *profile = self.store.profiles[indexPath.row]; BOOL active = [profile[@"id"] isEqual:self.store.activeProfileID]; cell.textLabel.text = profile[@"name"]; cell.detailTextLabel.text = [NSString stringWithFormat:@"%lu assigned app%@%@", (unsigned long)[profile[@"apps"] count], [profile[@"apps"] count] == 1 ? @"" : @"s", active ? @" · Active" : @""]; cell.imageView.image = [UIImage systemImageNamed:active ? @"checkmark.circle.fill" : @"person.crop.circle"]; cell.imageView.tintColor = active ? UIColor.systemGreenColor : UIColor.secondaryLabelColor;
    } else {
        NSArray *titles = @[@"Proxy Settings", @"Location", @"Export Backup", @"Import Backup", @"Device Information"]; NSArray *icons = @[@"network", @"map.fill", @"square.and.arrow.up", @"square.and.arrow.down", @"iphone.gen2"];
        cell.textLabel.text = titles[indexPath.row]; cell.imageView.image = [UIImage systemImageNamed:icons[indexPath.row]]; cell.imageView.tintColor = UIColor.systemGreenColor;
        if (indexPath.row < 2 && self.store.activeProfile) { UISwitch *toggle = [UISwitch new]; toggle.tag = indexPath.row; NSDictionary *profile = self.store.activeProfile; toggle.on = indexPath.row == 0 ? [profile[@"proxy"][@"enabled"] boolValue] : [profile[@"location"][@"enabled"] boolValue]; [toggle addTarget:self action:@selector(featureToggled:) forControlEvents:UIControlEventValueChanged]; cell.accessoryView = toggle; cell.accessoryType = UITableViewCellAccessoryNone; cell.detailTextLabel.text = toggle.on ? @"Enabled" : @"Disabled"; }
    }
    return cell;
}
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if (indexPath.section == 1) { [self showActionsForApp:self.visibleApps[indexPath.row] sourceView:[tableView cellForRowAtIndexPath:indexPath]]; return; }
    if (indexPath.section == 2) { [self.store activateProfileAtIndex:indexPath.row]; [tableView reloadData]; return; }
    if (indexPath.section != 3) return;
    if (!self.store.activeProfile && indexPath.row < 2) { [self alert:@"No active profile" message:@"Select an installed app and create a profile first."]; return; }
    switch (indexPath.row) { case 0: [self configureProxy]; break; case 1: [self configureLocation]; break; case 2: [self exportBackup]; break; case 3: [self importBackup]; break; default: [self showDiagnostics]; }
}
- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)style forRowAtIndexPath:(NSIndexPath *)indexPath { if (indexPath.section == 2 && style == UITableViewCellEditingStyleDelete) { [self.store deleteProfileAtIndex:indexPath.row]; [tableView reloadData]; } }
- (NSDictionary *)profileForBundleID:(NSString *)bundleID { for (NSDictionary *profile in self.store.profiles) if ([profile[@"apps"] containsObject:bundleID]) return profile; return nil; }
- (NSUInteger)indexForProfileID:(NSString *)profileID { return [self.store.profiles indexOfObjectPassingTest:^BOOL(NSDictionary *profile, NSUInteger idx, BOOL *stop) { return [profile[@"id"] isEqual:profileID]; }]; }
- (NSUInteger)activeIndex { return [self indexForProfileID:self.store.activeProfileID]; }
- (void)showActionsForApp:(NSDictionary *)app sourceView:(UIView *)sourceView {
    NSDictionary *assigned = [self profileForBundleID:app[@"bundleID"]]; UIAlertController *menu = [UIAlertController alertControllerWithTitle:app[@"name"] message:app[@"bundleID"] preferredStyle:UIAlertControllerStyleActionSheet];
    [menu addAction:[UIAlertAction actionWithTitle:@"Create New Profile" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { [self promptForProfileName:app[@"name"] completion:^(NSString *name) { [self.store addProfileNamed:name]; NSUInteger index = self.store.profiles.count - 1; [self.store activateProfileAtIndex:index]; [self.store addBundleID:app[@"bundleID"] toProfileAtIndex:index]; [self.tableView reloadData]; }]; }]];
    if (self.store.activeProfile) [menu addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Add to %@", self.store.activeProfile[@"name"]] style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { [self.store addBundleID:app[@"bundleID"] toProfileAtIndex:self.activeIndex]; [self.tableView reloadData]; }]];
    if (assigned) [menu addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Activate %@", assigned[@"name"]] style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { [self.store activateProfileAtIndex:[self indexForProfileID:assigned[@"id"]]]; [self.tableView reloadData]; }]];
    [menu addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; menu.popoverPresentationController.sourceView = sourceView; menu.popoverPresentationController.sourceRect = sourceView.bounds; [self presentViewController:menu animated:YES completion:nil];
}
- (void)promptForProfileName:(NSString *)suggested completion:(void (^)(NSString *))completion { UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"New App Profile" message:@"The selected app will be assigned and the profile activated automatically." preferredStyle:UIAlertControllerStyleAlert]; [alert addTextFieldWithConfigurationHandler:^(UITextField *field) { field.text = suggested; field.clearButtonMode = UITextFieldViewModeWhileEditing; }]; [alert addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; [alert addAction:[UIAlertAction actionWithTitle:@"Create" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { NSString *name = [alert.textFields.firstObject.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; if (name.length) completion(name); }]]; [self presentViewController:alert animated:YES completion:nil]; }
- (void)addProfile { [self promptForProfileName:@"New Profile" completion:^(NSString *name) { [self.store addProfileNamed:name]; [self.store activateProfileAtIndex:self.store.profiles.count - 1]; [self.tableView reloadData]; }]; }
- (void)featureToggled:(UISwitch *)sender { if (sender.tag == 0) [self.store setProxyEnabled:sender.on forProfileAtIndex:self.activeIndex]; else [self.store setLocationEnabled:sender.on forProfileAtIndex:self.activeIndex]; [self.tableView reloadData]; }
- (void)configureProxy { UIAlertController *a = [UIAlertController alertControllerWithTitle:@"Proxy Settings" message:@"Configure the active profile." preferredStyle:UIAlertControllerStyleAlert]; for (NSString *placeholder in @[@"Host", @"Port", @"Username (optional)", @"Password (optional)"]) [a addTextFieldWithConfigurationHandler:^(UITextField *field) { field.placeholder = placeholder; field.secureTextEntry = [placeholder hasPrefix:@"Password"]; if ([placeholder isEqualToString:@"Port"]) field.keyboardType = UIKeyboardTypeNumberPad; }]; NSDictionary *proxy = self.store.activeProfile[@"proxy"]; NSArray *values = @[proxy[@"host"] ?: @"", proxy[@"port"] ? [proxy[@"port"] stringValue] : @"", proxy[@"username"] ?: @"", proxy[@"password"] ?: @""]; [a.textFields enumerateObjectsUsingBlock:^(UITextField *field, NSUInteger idx, BOOL *stop) { field.text = values[idx]; }]; [a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; [a addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { [self.store setProxyHost:a.textFields[0].text port:[a.textFields[1].text integerValue] username:a.textFields[2].text password:a.textFields[3].text forProfileAtIndex:self.activeIndex]; [self.tableView reloadData]; }]]; [self presentViewController:a animated:YES completion:nil]; }
- (void)configureLocation { CHMapController *map = [CHMapController new]; map.store = self.store; map.profileIndex = self.activeIndex; [self presentViewController:[[UINavigationController alloc] initWithRootViewController:map] animated:YES completion:nil]; }
- (void)exportBackup { UIActivityViewController *share = [[UIActivityViewController alloc] initWithActivityItems:@[[self.store exportBackup]] applicationActivities:nil]; [self presentViewController:share animated:YES completion:nil]; }
- (void)importBackup { UIDocumentPickerViewController *picker = [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:@[UTTypeJSON, UTTypeData] asCopy:YES]; picker.delegate = self; picker.allowsMultipleSelection = NO; [self presentViewController:picker animated:YES completion:nil]; }
- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls { NSError *error = nil; if (urls.firstObject && [self.store importBackupFromURL:urls.firstObject error:&error]) { [self.tableView reloadData]; [self alert:@"Backup Imported" message:@"Profiles and settings were restored."]; } else [self alert:@"Import Failed" message:error.localizedDescription ?: @"The selected backup could not be imported."]; }
- (void)showDiagnostics { UIDevice *device = UIDevice.currentDevice; device.batteryMonitoringEnabled = YES; NSProcessInfo *process = NSProcessInfo.processInfo; NSDictionary *r = self.store.runtime; NSString *message = [NSString stringWithFormat:@"Model: %@\nSystem: %@\nName: %@\nVendor ID: %@\nScreen: %.0f × %.0f\nBattery: %@\nLocale: %@\nTimezone: %@\nMemory: %.1f GB\nFree disk: %.1f GB\nRuntime: %@\nThird-party apps: %lu\nProfiles: %lu\n\nIMEI, serial number and hardware UDID are protected by iOS and are not collected.", device.model, device.systemVersion, device.name, device.identifierForVendor.UUIDString ?: @"Unavailable", UIScreen.mainScreen.bounds.size.width, UIScreen.mainScreen.bounds.size.height, device.batteryState == UIDeviceBatteryStateUnknown ? @"Unknown" : [NSString stringWithFormat:@"%.0f%%", device.batteryLevel * 100], NSLocale.currentLocale.localeIdentifier, NSTimeZone.localTimeZone.name, process.physicalMemory / 1073741824.0, [self freeDiskGB], r.count ? @"Connected" : @"Waiting for respring", (unsigned long)self.installedApps.count, (unsigned long)self.store.profiles.count]; [self alert:@"Device Information" message:message]; }
- (double)freeDiskGB { return [[[[NSFileManager defaultManager] attributesOfFileSystemForPath:@"/" error:nil] objectForKey:NSFileSystemFreeSize] doubleValue] / 1073741824.0; }
- (void)alert:(NSString *)title message:(NSString *)message { UIAlertController *alert = [UIAlertController alertControllerWithTitle:title message:message preferredStyle:UIAlertControllerStyleAlert]; [alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]]; [self presentViewController:alert animated:YES completion:nil]; }
@end
