#import "CHRootViewController.h"
#import "CHProfileStore.h"
#import "CHInstalledAppCatalog.h"
#import "CHAppLibraryController.h"
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>

@interface CHRootViewController () <UIDocumentPickerDelegate>
@property(nonatomic, strong) CHProfileStore *store;
@property(nonatomic, copy) NSArray<NSDictionary *> *applications;
@end

@implementation CHRootViewController
- (void)viewDidLoad { [super viewDidLoad]; self.title = @"Overview"; self.store = [CHProfileStore new]; self.navigationController.navigationBar.prefersLargeTitles = YES; self.navigationController.navigationBar.tintColor = UIColor.systemGreenColor; self.tableView.backgroundColor = UIColor.systemGroupedBackgroundColor; [self buildHeader]; [self reloadApplications]; }
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; [self reloadApplications]; }
- (void)reloadApplications { self.applications = [CHInstalledAppCatalog thirdPartyApplications]; [self.tableView reloadData]; }
- (void)buildHeader { UIView *container = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, 150)]; UIView *card = [[UIView alloc] initWithFrame:CGRectMake(16, 12, self.view.bounds.size.width - 32, 122)]; card.backgroundColor = UIColor.secondarySystemGroupedBackgroundColor; card.layer.cornerRadius = 22; card.layer.shadowColor = UIColor.blackColor.CGColor; card.layer.shadowOpacity = .08; card.layer.shadowRadius = 12; card.layer.shadowOffset = CGSizeMake(0, 4); UIImageView *icon = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"AppIcon1024"]]; icon.frame = CGRectMake(20, 20, 82, 82); icon.layer.cornerRadius = 18; icon.layer.masksToBounds = YES; [card addSubview:icon]; UILabel *title = [[UILabel alloc] initWithFrame:CGRectMake(120, 28, card.bounds.size.width - 140, 34)]; title.text = @"Chameleon"; title.font = [UIFont systemFontOfSize:28 weight:UIFontWeightBold]; [card addSubview:title]; UILabel *subtitle = [[UILabel alloc] initWithFrame:CGRectMake(120, 65, card.bounds.size.width - 140, 42)]; subtitle.text = @"App profiles, clearly separated."; subtitle.font = [UIFont systemFontOfSize:15 weight:UIFontWeightMedium]; subtitle.textColor = UIColor.secondaryLabelColor; subtitle.numberOfLines = 2; [card addSubview:subtitle]; [container addSubview:card]; self.tableView.tableHeaderView = container; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return 3; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return section == 0 ? 1 : (section == 1 ? 1 : 3); }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return @[@"Current Profile", @"Workspace", @"Maintenance"][section]; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { if (section == 0) return self.store.activeProfile ? @"Tap to enter the running app profile and change its settings." : @"No profile is running. Open Applications & Profiles to create one."; return nil; }
- (NSDictionary *)applicationForBundleID:(NSString *)bundleID { for (NSDictionary *app in self.applications) if ([app[@"bundleID"] isEqual:bundleID]) return app; return nil; }
- (NSDictionary *)applicationForProfile:(NSDictionary *)profile { NSString *bundleID = [profile[@"apps"] firstObject]; return bundleID ? [self applicationForBundleID:bundleID] : nil; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    if (indexPath.section == 0) { NSDictionary *profile = self.store.activeProfile; NSDictionary *app = [self applicationForProfile:profile]; cell.textLabel.text = profile ? profile[@"name"] : @"No active profile"; cell.detailTextLabel.text = profile ? [NSString stringWithFormat:@"%@ · Running", app[@"name"] ?: [profile[@"apps"] firstObject] ?: @"App profile"] : @"Choose an app and create a profile"; cell.imageView.image = app[@"icon"] ?: [UIImage systemImageNamed:profile ? @"checkmark.shield.fill" : @"moon.zzz.fill"]; cell.imageView.tintColor = UIColor.systemGreenColor; cell.accessoryType = profile ? UITableViewCellAccessoryDisclosureIndicator : UITableViewCellAccessoryNone; }
    else if (indexPath.section == 1) { cell.textLabel.text = @"Applications & Profiles"; cell.detailTextLabel.text = [NSString stringWithFormat:@"%lu installed apps · Profiles are grouped per app", (unsigned long)self.applications.count]; cell.imageView.image = [UIImage systemImageNamed:@"square.grid.2x2.fill"]; cell.imageView.tintColor = UIColor.systemGreenColor; }
    else { NSArray *titles = @[@"Export Backup", @"Import Backup", @"Device Information"]; NSArray *details = @[@"Save every app profile", @"Restore a Chameleon backup", @"Device and runtime diagnostics"]; NSArray *icons = @[@"square.and.arrow.up", @"square.and.arrow.down", @"iphone.gen2"]; cell.textLabel.text = titles[indexPath.row]; cell.detailTextLabel.text = details[indexPath.row]; cell.imageView.image = [UIImage systemImageNamed:icons[indexPath.row]]; cell.imageView.tintColor = UIColor.systemGreenColor; }
    return cell;
}
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath { [tableView deselectRowAtIndexPath:indexPath animated:YES]; if (indexPath.section == 0) { NSDictionary *profile = self.store.activeProfile; NSDictionary *app = [self applicationForProfile:profile]; if (profile && app) [self.navigationController pushViewController:[[CHProfileDetailController alloc] initWithStore:self.store application:app profileID:profile[@"id"]] animated:YES]; return; } if (indexPath.section == 1) { [self.navigationController pushViewController:[[CHAppLibraryController alloc] initWithStore:self.store] animated:YES]; return; } if (indexPath.row == 0) [self exportBackup]; else if (indexPath.row == 1) [self importBackup]; else [self showDiagnostics]; }
- (void)exportBackup { UIActivityViewController *share = [[UIActivityViewController alloc] initWithActivityItems:@[[self.store exportBackup]] applicationActivities:nil]; [self presentViewController:share animated:YES completion:nil]; }
- (void)importBackup { UIDocumentPickerViewController *picker = [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:@[UTTypeJSON, UTTypeData] asCopy:YES]; picker.delegate = self; picker.allowsMultipleSelection = NO; [self presentViewController:picker animated:YES completion:nil]; }
- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls { NSError *error = nil; if (urls.firstObject && [self.store importBackupFromURL:urls.firstObject error:&error]) { [self.tableView reloadData]; [self alert:@"Backup Imported" message:@"Profiles and settings were restored."]; } else [self alert:@"Import Failed" message:error.localizedDescription ?: @"The selected backup could not be imported."]; }
- (void)showDiagnostics { UIDevice *device = UIDevice.currentDevice; device.batteryMonitoringEnabled = YES; NSProcessInfo *process = NSProcessInfo.processInfo; NSDictionary *runtime = self.store.runtime; NSString *message = [NSString stringWithFormat:@"Model: %@\nSystem: %@\nName: %@\nVendor ID: %@\nScreen: %.0f × %.0f\nBattery: %@\nLocale: %@\nTimezone: %@\nMemory: %.1f GB\nFree disk: %.1f GB\nRuntime: %@\nInstalled apps: %lu\nApp profiles: %lu\n\nIMEI, serial number and hardware UDID are protected by iOS and are not collected.", device.model, device.systemVersion, device.name, device.identifierForVendor.UUIDString ?: @"Unavailable", UIScreen.mainScreen.bounds.size.width, UIScreen.mainScreen.bounds.size.height, device.batteryState == UIDeviceBatteryStateUnknown ? @"Unknown" : [NSString stringWithFormat:@"%.0f%%", device.batteryLevel * 100], NSLocale.currentLocale.localeIdentifier, NSTimeZone.localTimeZone.name, process.physicalMemory / 1073741824.0, [self freeDiskGB], runtime.count ? @"Connected" : @"Waiting for respring", (unsigned long)self.applications.count, (unsigned long)self.store.profiles.count]; [self alert:@"Device Information" message:message]; }
- (double)freeDiskGB { return [[[[NSFileManager defaultManager] attributesOfFileSystemForPath:@"/" error:nil] objectForKey:NSFileSystemFreeSize] doubleValue] / 1073741824.0; }
- (void)alert:(NSString *)title message:(NSString *)message { UIAlertController *alert = [UIAlertController alertControllerWithTitle:title message:message preferredStyle:UIAlertControllerStyleAlert]; [alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]]; [self presentViewController:alert animated:YES completion:nil]; }
@end
